name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Run nvm use to set node version
        shell: bash -l {0} 
        run: nvm install
      - name: Install Dependencies
        run: cd frontend/ && npm ci
      - name: Build
        run: cd frontend/ && CI="false" npm run build #TODO: Remove this after warnings are fixed
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: frontend-build
          path: frontend/build
  build-functions:
    name: Build functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Run nvm use to set node version
        shell: bash -l {0} 
        run: cd functions && nvm install
      - name: Install Dependencies
        run: cd functions/ && npm ci
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: functions-build
          path: functions
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Download frontend artifact
        uses: actions/download-artifact@main
        with:
          name: frontend-build
          path: frontend/build
      - name: Download function artifact
        uses: actions/download-artifact@main
        with:
          name: functions-build
          path: functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
