name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Run nvm use to set node version
      - uses: dcodeIO/setup-node-nvm@master
      - name: Install Dependencies
        run: cd frontend/ && npm install
      - name: Build
        run: cd frontend/ && CI="false" npm run build #TODO: Remove this after warnings are fixed
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: frontend/dist
          path: frontend/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: frontend/dist
          path: frontend/dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
